on:
  push:
    branches: [ main ]
  workflow_dispatch: 

name: build


env:
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_REGISTRY: LeonaKurtaj
  DOCKER_REPOSITORY: web-client-sample

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install dependencies
      id: npm-install
      run: |
        npm install
  
    # - name: Run unit tests
    #   id: run-unit-tests
    #   run: |
    #     npm run test

    - name: Build, tag, and push the image to Docker Hub
      id: build-image
      run: |
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest .
        docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
        docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG

        echo "Pushing image to ECR..."
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest

        echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
